import { describe, expect, it } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { mergeWithExisting } from '../src/core/design-generator.js';

function tempFile(content: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cdd-design-doc-'));
  const filePath = path.join(dir, 'DESIGN.md');
  fs.writeFileSync(filePath, content, 'utf-8');
  return filePath;
}

describe('mergeWithExisting design docs', () => {
  it('replaces an existing generated design document', () => {
    const existingPath = tempFile([
      '# Design System — demo',
      '',
      '> Auto-generated by **code-drive design**. Design tokens extracted from source code.',
      '',
      '- **Font Family:** `16px`',
    ].join('\n'));
    const newContent = [
      '# Design System — demo',
      '',
      '> Auto-generated by **code-drive design**. Design tokens extracted from source code.',
      '',
      '- **Font Family:** `Inter`',
    ].join('\n');

    const merged = mergeWithExisting(newContent, existingPath);

    expect(merged).toBe(newContent);
    expect(merged).not.toContain('16px');
  });

  it('preserves manual notes after new generated content', () => {
    const existingPath = tempFile('# Design Notes\n\nKeep the checkout button blue.\n');
    const newContent = [
      '# Design System — demo',
      '',
      '> Auto-generated by **code-drive design**. Design tokens extracted from source code.',
    ].join('\n');

    const merged = mergeWithExisting(newContent, existingPath);

    expect(merged).toContain(newContent);
    expect(merged).toContain('Keep the checkout button blue.');
  });
});
