import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';
import type { AnalysisScopeOptions } from '../core/analysis-scope.js';
import { collectReviewFindings } from '../core/review-rules.js';
import type { ReviewFinding } from '../core/review-rules.js';

interface ReviewOptions {
  readonly output?: string;
  readonly includeTests?: boolean;
  readonly maxFindings?: string | number;
}

function parseMaxFindings(raw: string | number | undefined): number {
  if (typeof raw === 'number' && Number.isFinite(raw)) return Math.max(1, Math.floor(raw));
  if (typeof raw !== 'string') return 20;

  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) ? Math.max(1, parsed) : 20;
}

function printFindingGroup(
  title: string,
  findings: ReviewFinding[],
  maxFindings: number,
  color: (message: string) => string,
  icon: string,
): void {
  if (findings.length === 0) return;

  console.log(color(`${title} (${findings.length}):`));
  for (const finding of findings.slice(0, maxFindings)) {
    const loc = finding.file ? chalk.dim(` [${finding.file}${finding.line ? `:${finding.line}` : ''}]`) : '';
    console.log(`  ${color(icon)} ${finding.message}${loc}`);
  }
  if (findings.length > maxFindings) {
    console.log(chalk.dim(`  ... ${findings.length - maxFindings} more hidden; use --max-findings ${findings.length} to show all`));
  }
  console.log('');
}

// ─── Command ──────────────────────────────────────────────────────────

export async function reviewCommand(dir: string, options: ReviewOptions): Promise<void> {
  const targetDir = path.resolve(dir);
  const analysisOptions: AnalysisScopeOptions = { includeTests: options.includeTests };
  const maxFindings = parseMaxFindings(options.maxFindings);

  if (!fs.existsSync(targetDir)) {
    throw new Error(`Directory not found: ${targetDir}`);
  }

  console.log(chalk.cyan('Running CDD review...'));

  const summary = collectReviewFindings(targetDir, analysisOptions);
  const findings = summary.findings;

  // ── Summary ──
  const errors = findings.filter((f) => f.severity === 'error');
  const warnings = findings.filter((f) => f.severity === 'warn');
  const infos = findings.filter((f) => f.severity === 'info');

  console.log('');
  console.log(chalk.bold(`CDD Review — ${summary.projectName} v${summary.version}`));
  console.log(
    chalk.dim(
      `  ${summary.functionCount} functions, ${summary.classCount} classes, ${summary.interfaceCount} interfaces`,
    ),
  );
  console.log('');

  if (findings.length === 0) {
    console.log(chalk.green('✓ No issues found. Your code follows CDD principles!'));
    return;
  }

  printFindingGroup('Errors', errors, maxFindings, chalk.bold.red, '✖');
  printFindingGroup('Warnings', warnings, maxFindings, chalk.bold.yellow, '⚠');
  printFindingGroup('Info', infos, maxFindings, chalk.bold.cyan, 'ℹ');

  if (options.output) {
    const outputPath = path.resolve(options.output);
    const reportLines: string[] = [
      `# CDD Review Report — ${summary.projectName}`,
      '',
      `**${findings.length} findings:** ${errors.length} errors, ${warnings.length} warnings, ${infos.length} info`,
      '',
      ...findings.map(
        (f) =>
          `- [${f.severity.toUpperCase()}] ${f.rule}: ${f.message}${f.file ? ` (${f.file}${f.line ? `:${f.line}` : ''})` : ''}`,
      ),
      '',
      '*Generated by code-drive*',
    ];
    fs.writeFileSync(outputPath, reportLines.join('\n'), 'utf-8');
    console.log(chalk.dim(`  Report saved: ${outputPath}`));
  }
}
