import type { DesignTokens } from './design-extractor.js';
import * as fs from 'node:fs';
import * as path from 'node:path';

// ─── Output ───────────────────────────────────────────────────────────

export interface DocResult {
  filePath: string;
  content: string;
}

export function writeDocs(results: DocResult[]): void {
  for (const r of results) {
    const dir = path.dirname(r.filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(r.filePath, r.content, 'utf-8');
  }
}

// ─── Color Swatch ──────────────────────────────────────────────────────

function colorSwatch(value: string): string {
  const hex = value.replace('#', '');
  return `<span style="display:inline-block;width:16px;height:16px;background:#${hex};border:1px solid #ccc;border-radius:3px;"></span>`;
}

function isHexColor(v: string): boolean {
  return /^#[0-9a-fA-F]{3,8}$/.test(v.trim());
}

function hasDesignTokens(tokens: DesignTokens): boolean {
  return tokens.colors.length > 0
    || tokens.typography.length > 0
    || tokens.spacing.length > 0
    || tokens.borderRadius.length > 0
    || tokens.shadows.length > 0
    || tokens.styleUsage.length > 0
    || tokens.hasTailwind;
}

function appendEmptyDesignGuidance(lines: string[]): void {
  lines.push('## No design tokens found');
  lines.push('');
  lines.push('CDD scanned the project but did not find CSS custom properties, Tailwind theme values, or TypeScript theme constants that look like design tokens.');
  lines.push('');
  lines.push('## AI Usage Guidance');
  lines.push('');
  lines.push('- Treat this file as a signal that the project does not yet expose a reusable design system in code.');
  lines.push('- Before UI work, inspect existing components and styles directly, then add reusable tokens when introducing repeated colors, spacing, typography, radius, or shadow values.');
  lines.push('- Prefer CSS custom properties, Tailwind theme extensions, or exported theme constants so future `cdd design` runs can document them here.');
  lines.push('- Run `cdd design` again after adding or changing design tokens.');
  lines.push('');
  lines.push('## Token Sources CDD Detects');
  lines.push('');
  lines.push('- CSS custom properties such as `--color-primary`, `--font-sans`, `--space-4`, `--radius-md`, and `--shadow-card`.');
  lines.push('- TypeScript constants named `colors`, `theme`, `tokens`, `palette`, `styles`, or `designSystem`.');
  lines.push('- Tailwind config files named `tailwind.config.js`, `tailwind.config.ts`, `tailwind.config.mjs`, or `tailwind.config.mts`.');
  lines.push('');
}

// ─── Generation ────────────────────────────────────────────────────────

export function generateDesignDoc(tokens: DesignTokens): string {
  const lines: string[] = [];

  lines.push(`# Design System — ${tokens.projectName}`);
  lines.push('');
  lines.push('> Auto-generated by **code-drive design**. Design tokens extracted from source code.');
  lines.push('');

  const toc: string[] = [];
  if (tokens.colors.length) toc.push('- [Color Palette](#color-palette)');
  if (tokens.typography.length) toc.push('- [Typography](#typography)');
  if (tokens.spacing.length) toc.push('- [Spacing](#spacing)');
  if (tokens.borderRadius.length) toc.push('- [Border Radius](#border-radius)');
  if (tokens.shadows.length) toc.push('- [Shadows](#shadows)');
  if (tokens.styleUsage.length) toc.push('- [Detected Style Usage](#detected-style-usage)');
  if (tokens.hasTailwind) toc.push('- [Tailwind CSS](#tailwind-css)');

  if (toc.length > 0) {
    lines.push('## Table of Contents');
    lines.push('');
    lines.push(...toc);
    lines.push('');
  } else if (!hasDesignTokens(tokens)) {
    appendEmptyDesignGuidance(lines);
  }

  // ── Color Palette ──────────────────────────────────────────────────
  if (tokens.colors.length) {
    lines.push('## Color Palette');
    lines.push('');
    lines.push(`| Swatch | Name | Value | Category | Source |`);
    lines.push(`|--------|------|-------|----------|--------|`);

    // Sort by category then name
    const sorted = [...tokens.colors].sort((a, b) => {
      if (a.category !== b.category) return a.category.localeCompare(b.category);
      return a.name.localeCompare(b.name);
    });

    for (const c of sorted) {
      const swatch = isHexColor(c.value) ? colorSwatch(c.value) : '—';
      const sourceShort = c.source.split('/').pop() || c.source;
      lines.push(`| ${swatch} | \`${c.name}\` | \`${c.value}\` | ${c.category} | \`${sourceShort}\` |`);
    }
    lines.push('');
  }

  // ── Typography ─────────────────────────────────────────────────────
  if (tokens.typography.length) {
    lines.push('## Typography');
    lines.push('');

    for (const t of tokens.typography) {
      if (t.fontFamily) {
        lines.push(`- **Font Family:** \`${t.fontFamily}\``);
      }
      if (t.sizes && t.sizes.length) {
        lines.push('');
        lines.push('  | Name | Value |');
        lines.push('  |------|-------|');
        for (const s of t.sizes) {
          lines.push(`  | \`${s.name}\` | \`${s.value}\` |`);
        }
      }
      if (t.weights && t.weights.length) {
        lines.push('');
        lines.push('  | Weight | Value |');
        lines.push('  |--------|-------|');
        for (const w of t.weights) {
          lines.push(`  | \`${w.name}\` | \`${w.value}\` |`);
        }
      }
      lines.push('');
    }
  }

  // ── Spacing ────────────────────────────────────────────────────────
  if (tokens.spacing.length) {
    lines.push('## Spacing');
    lines.push('');
    lines.push('| Name | Value | Source |');
    lines.push('|------|-------|--------|');
    for (const s of tokens.spacing) {
      const sourceShort = s.source.split('/').pop() || s.source;
      lines.push(`| \`${s.name}\` | \`${s.value}\` | \`${sourceShort}\` |`);
    }
    lines.push('');
  }

  // ── Border Radius ──────────────────────────────────────────────────
  if (tokens.borderRadius.length) {
    lines.push('## Border Radius');
    lines.push('');
    lines.push('| Name | Value | Source |');
    lines.push('|------|-------|--------|');
    for (const r of tokens.borderRadius) {
      const sourceShort = r.source.split('/').pop() || r.source;
      lines.push(`| \`${r.name}\` | \`${r.value}\` | \`${sourceShort}\` |`);
    }
    lines.push('');
  }

  // ── Shadows ────────────────────────────────────────────────────────
  if (tokens.shadows.length) {
    lines.push('## Shadows');
    lines.push('');
    lines.push('| Name | Value | Source |');
    lines.push('|------|-------|--------|');
    for (const s of tokens.shadows) {
      const sourceShort = s.source.split('/').pop() || s.source;
      lines.push(`| \`${s.name}\` | \`${s.value}\` | \`${sourceShort}\` |`);
    }
    lines.push('');
  }

  if (tokens.styleUsage.length) {
    lines.push('## Detected Style Usage');
    lines.push('');
    lines.push('These are concrete style rules found in the current project. They may not be reusable tokens yet, but they describe the design already present in source files.');
    lines.push('');
    lines.push('| Selector | Property | Value | Category | Source |');
    lines.push('|----------|----------|-------|----------|--------|');
    for (const usage of tokens.styleUsage.slice(0, 80)) {
      const sourceShort = usage.source.split('/').pop() || usage.source;
      for (const property of usage.properties) {
        lines.push(`| \`${usage.selector}\` | \`${property.name}\` | \`${property.value}\` | ${property.category} | \`${sourceShort}\` |`);
      }
    }
    if (tokens.styleUsage.length > 80) {
      lines.push('');
      lines.push(`> ${tokens.styleUsage.length - 80} additional selectors omitted to keep this document readable.`);
    }
    lines.push('');
  }

  // ── Tailwind ───────────────────────────────────────────────────────
  if (tokens.hasTailwind) {
    lines.push('## Tailwind CSS');
    lines.push('');
    lines.push('> Tailwind CSS configuration detected. Run `cdd design` with a Tailwind project to extract theme values.');
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Merge with Existing ──────────────────────────────────────────────

export function mergeWithExisting(newContent: string, existingPath: string): string {
  let existing = '';
  try {
    existing = fs.readFileSync(existingPath, 'utf-8');
  } catch {
    return newContent;
  }
  if (existing.includes('Auto-generated by **code-drive design**')) {
    return newContent;
  }
  return newContent + '\n\n---\n\n' + existing;
}
