import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ProjectInfo, CodeAnnotation, ModuleStructure } from './analyzer.js';

export interface DocResult {
  filePath: string;
  content: string;
}

export function generateReadmeDocs(project: ProjectInfo, annotations: CodeAnnotation[]): string {
  const lines: string[] = [];

  lines.push(`# ${project.name}`);
  lines.push('');
  lines.push(`> Auto-generated by code-drive (CDD)`);
  lines.push('');
  lines.push(`**Version:** ${project.version}`);
  lines.push(`**Language:** ${project.language}`);
  lines.push(`**Source files:** ${project.sourceFiles.length}`);
  lines.push('');

  if (project.dependencies.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    for (const dep of project.dependencies) {
      lines.push(`- ${dep}`);
    }
    lines.push('');
  }

  if (annotations.length > 0) {
    lines.push('## Code Annotations');
    lines.push('');
    lines.push('| File | Line | Tag | Note |');
    lines.push('|------|------|-----|------|');
    for (const ann of annotations) {
      lines.push(`| ${ann.file} | ${ann.line} | \`${ann.tag}\` | ${ann.content} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function generateArchitectureSpec(
  modules: ModuleStructure[],
  project: ProjectInfo,
): string {
  const lines: string[] = [];

  lines.push(`# Architecture Specification — ${project.name}`);
  lines.push('');
  lines.push(`> Auto-generated by code-drive. Source: \`${project.language}\``);
  lines.push('');
  lines.push(`## Overview`);
  lines.push('');
  lines.push(`**Source files:** ${project.sourceFiles.length}`);
  lines.push(`**Entry points:** ${project.entryPoints.join(', ')}`);
  lines.push('');
  lines.push(`## Module Structure`);
  lines.push('');

  if (modules.length === 0) {
    lines.push('No modules detected. Ensure your source code is in a structured directory.');
  } else {
    for (const mod of modules) {
      lines.push(`### ${mod.name}`);
      lines.push('');
      lines.push(`**Path:** \`${mod.path}\``);
      lines.push(`**Files:** ${mod.exports.length}`);
      lines.push('');
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by code-drive — Code is the source of truth.*');

  return lines.join('\n');
}

export function generateCddConfig(dir: string): Record<string, unknown> {
  return {
    version: '0.1.0',
    sourceDir: 'src',
    docDir: 'docs',
    language: 'typescript',
    conventions: {
      modulePattern: '**/index.ts',
      annotationStyle: 'tsdoc',
    },
    generatedAt: new Date().toISOString(),
    projectRoot: dir,
  };
}

export function writeDocs(results: DocResult[]): void {
  for (const result of results) {
    const dir = path.dirname(result.filePath);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(result.filePath, result.content, 'utf-8');
  }
}
