import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
  ProjectInfo,
  FunctionDecl,
  ClassDecl,
  InterfaceDecl,
  ImportEdge,
  CodeAnnotation,
} from './analyzer.js';
import { groupByModule } from './module-map.js';
export { generateCddConfig } from './cdd-config-generator.js';

// ─── Types ────────────────────────────────────────────────────────────

export interface DocResult {
  filePath: string;
  content: string;
}

// ─── README Docs ──────────────────────────────────────────────────────

export function generateReadmeDocs(
  project: ProjectInfo,
  functions: FunctionDecl[],
  classes: ClassDecl[],
  interfaces: InterfaceDecl[],
  annotations: CodeAnnotation[],
): string {
  const lines: string[] = [];

  lines.push(`# ${project.name}`);
  lines.push('');
  lines.push(`> Auto-generated by code-drive — Code is the single source of truth.`);
  lines.push('');

  lines.push(`## Project Info`);
  lines.push('');
  lines.push(`- **Version:** ${project.version}`);
  lines.push(`- **Language:** ${project.language}`);
  lines.push(`- **Source files:** ${project.sourceFiles.length}`);
  lines.push(`- **Entry points:** ${project.entryPoints.join(', ')}`);
  lines.push('');

  if (project.dependencies.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    for (const dep of project.dependencies) {
      lines.push(`- \`${dep}\``);
    }
    lines.push('');
  }

  // ── Functions ──
  const exportedFns = functions.filter((f) => f.exportKind !== 'none');
  if (exportedFns.length > 0) {
    lines.push('## Public API — Functions');
    lines.push('');
    lines.push('| Name | File | Parameters | Returns |');
    lines.push('|------|------|------------|---------|');
    for (const fn of exportedFns) {
      lines.push(
        `| \`${fn.name}\` | \`${fn.file}:${fn.line}\` | ${fn.params.length > 5 ? `${fn.params.length} params` : fn.params.join(', ')} | ${fn.returnType || '—'} |`,
      );
    }
    lines.push('');
  }

  // ── Classes ──
  const exportedClasses = classes.filter((c) => c.exportKind !== 'none');
  if (exportedClasses.length > 0) {
    lines.push('## Public API — Classes');
    lines.push('');
    for (const cls of exportedClasses) {
      lines.push(`### \`${cls.name}\``);
      lines.push('');
      lines.push(`- **File:** \`${cls.file}:${cls.line}\``);
      if (cls.extendsClause) lines.push(`- **Extends:** \`${cls.extendsClause}\``);
      if (cls.methods.length > 0) lines.push(`- **Methods:** ${cls.methods.join(', ')}`);
      if (cls.properties.length > 0) lines.push(`- **Properties:** ${cls.properties.join(', ')}`);
      lines.push('');
    }
  }

  // ── Interfaces ──
  const exportedIfaces = interfaces.filter((i) => i.exportKind !== 'none');
  if (exportedIfaces.length > 0) {
    lines.push('## Public API — Interfaces');
    lines.push('');
    for (const iface of exportedIfaces) {
      lines.push(`- \`${iface.name}\` — ${iface.members.join(', ')}`);
    }
    lines.push('');
  }

  // ── Annotations ──
  if (annotations.length > 0) {
    lines.push('## Code Annotations');
    lines.push('');
    lines.push('| File | Line | Tag | Note |');
    lines.push('|------|------|-----|------|');
    for (const ann of annotations) {
      lines.push(`| \`${ann.file}\` | ${ann.line} | \`${ann.tag}\` | ${ann.content} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [code-drive](https://github.com/eastjin616/code-drive)*');

  return lines.join('\n');
}

// ─── Per-File API Docs ────────────────────────────────────────────────

export function generateApiDocs(
  filePath: string,
  functions: FunctionDecl[],
  classes: ClassDecl[],
  interfaces: InterfaceDecl[],
): string {
  const lines: string[] = [];

  lines.push(`# \`${filePath}\``);
  lines.push('');
  lines.push('> Auto-generated API reference.');
  lines.push('');

  if (functions.length > 0) {
    lines.push('## Functions');
    lines.push('');
    for (const fn of functions) {
      lines.push(`### ${fn.exportKind !== 'none' ? 'export ' : ''}function \`${fn.name}\``);
      lines.push('');
      if (fn.doc) {
        lines.push(fn.doc);
        lines.push('');
      }
      lines.push('```typescript');
      const sig = `${fn.exportKind !== 'none' ? 'export ' : ''}function ${fn.name}(${fn.params.join(', ')})${fn.returnType ? `: ${fn.returnType}` : ''}`;
      lines.push(sig);
      lines.push('```');
      lines.push('');
    }
  }

  if (classes.length > 0) {
    lines.push('## Classes');
    lines.push('');
    for (const cls of classes) {
      lines.push(`### ${cls.exportKind !== 'none' ? 'export ' : ''}class \`${cls.name}\``);
      lines.push('');
      if (cls.doc) {
        lines.push(cls.doc);
        lines.push('');
      }
      if (cls.extendsClause) {
        lines.push(`**Extends:** \`${cls.extendsClause}\``);
        lines.push('');
      }
      if (cls.methods.length > 0) {
        lines.push('**Methods:**');
        lines.push('');
        for (const m of cls.methods) {
          lines.push(`- \`${m}()\``);
        }
        lines.push('');
      }
      if (cls.properties.length > 0) {
        lines.push('**Properties:**');
        lines.push('');
        for (const p of cls.properties) {
          lines.push(`- \`${p}\``);
        }
        lines.push('');
      }
    }
  }

  if (interfaces.length > 0) {
    lines.push('## Interfaces');
    lines.push('');
    for (const iface of interfaces) {
      lines.push(`### ${iface.exportKind !== 'none' ? 'export ' : ''}interface \`${iface.name}\``);
      lines.push('');
      if (iface.doc) {
        lines.push(iface.doc);
        lines.push('');
      }
      lines.push('**Members:**');
      for (const m of iface.members) {
        lines.push(`- \`${m}\``);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ─── Architecture Spec ────────────────────────────────────────────────

export function generateArchitectureSpec(
  project: ProjectInfo,
  functions: FunctionDecl[],
  classes: ClassDecl[],
  interfaces: InterfaceDecl[],
  imports: ImportEdge[],
): string {
  const lines: string[] = [];

  lines.push(`# Architecture Specification — ${project.name}`);
  lines.push('');
  lines.push(`> Auto-generated by code-drive. Source language: \`${project.language}\``);
  lines.push('');

  lines.push('## Overview');
  lines.push('');
  lines.push(`- **Source files:** ${project.sourceFiles.length}`);
  lines.push(`- **Entry points:** ${project.entryPoints.join(', ')}`);
  lines.push(`- **Dependencies:** ${project.dependencies.length}`);
  lines.push(
    `- **Exported functions:** ${functions.filter((f) => f.exportKind !== 'none').length}`,
  );
  lines.push(`- **Exported classes:** ${classes.filter((c) => c.exportKind !== 'none').length}`);
  lines.push(
    `- **Exported interfaces:** ${interfaces.filter((i) => i.exportKind !== 'none').length}`,
  );
  lines.push('');

  // ── Dependency Graph ──
  if (imports.length > 0) {
    lines.push('## Dependency Graph');
    lines.push('');
    lines.push('| Source | Target | Symbols |');
    lines.push('|--------|--------|---------|');
    for (const edge of imports.slice(0, 40)) {
      lines.push(`| \`${edge.from}\` | \`${edge.to}\` | ${edge.symbols.join(', ')} |`);
    }
    if (imports.length > 40) {
      lines.push(`| _… and ${imports.length - 40} more imports_ | | |`);
    }
    lines.push('');
  }

  // ── Module Map ──
  const modules = groupByModule(project.sourceFiles);
  if (modules.length > 0) {
    lines.push('## Module Map');
    lines.push('');
    for (const mod of modules) {
      lines.push(`### \`${mod.name}/\``);
      lines.push('');
      for (const file of mod.files) {
        lines.push(`- \`${file}\``);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [code-drive](https://github.com/eastjin616/code-drive)*');

  return lines.join('\n');
}

// ─── File I/O ─────────────────────────────────────────────────────────

export function writeDocs(results: DocResult[]): void {
  for (const result of results) {
    const dir = path.dirname(result.filePath);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(result.filePath, result.content, 'utf-8');
  }
}
